# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54607e303ef53a059ce421ae45f5ed6d02eff4082a8086915bc09d83da6d29e87af1e939ca5e778ad02fb0062b7bb36198b454bc393d78b15fe85e71129d992a

test:
  secret_key_base: 39e3ca5ec0030473dbd326bab84aa179ca3ad5489c783b56feccb8c1ccb3dc14bcb7b4ce81b30b5117d8d5edc16170bd5b4313df695cb5e807fb34bc9e7a585e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
